services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
  worker:
    build: ./python_worker
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - ./python_worker:/app

volumes:
    pg_data:
    redis_data:
