spring.application.name=deep_vibe
spring.jpa.hibernate.ddl-auto=update
spring.config.import=optional:file:.env[.properties]
spring.task.scheduling.pool.size=5

logging.level.org.springframework.boot.docker.compose=DEBUG

